import type { RequestStatus, RoleCode } from "@/types/domain";

export const ALLOWED_TRANSITIONS: Record<RequestStatus, RequestStatus[]> = {
  NEW: ["PRELIM_CHECKED"],
  PRELIM_CHECKED: ["WAITING_SURVEY_ASSIGNMENT"],
  WAITING_SURVEY_ASSIGNMENT: ["WAITING_SURVEYOR_DOCUMENT_REVIEW"],
  WAITING_SURVEYOR_DOCUMENT_REVIEW: ["DOCUMENT_READY_FOR_SURVEY", "DOCUMENT_INCOMPLETE", "NEED_MORE_INFO"],
  DOCUMENT_READY_FOR_SURVEY: ["SURVEY_SCHEDULED"],
  DOCUMENT_INCOMPLETE: ["WAITING_SURVEYOR_DOCUMENT_REVIEW"],
  NEED_MORE_INFO: ["WAITING_SURVEYOR_DOCUMENT_REVIEW"],
  SURVEY_SCHEDULED: ["SURVEY_COMPLETED"],
  SURVEY_COMPLETED: ["METER_WAITING_ICS", "EXT_WAITING_SUMMARY"],
  METER_WAITING_ICS: ["METER_WAITING_INVOICE"],
  METER_WAITING_INVOICE: ["METER_WAITING_PAYMENT"],
  METER_WAITING_PAYMENT: ["METER_WAITING_APPROVAL"],
  METER_WAITING_APPROVAL: ["METER_WAITING_INSTALL_QUEUE"],
  METER_WAITING_INSTALL_QUEUE: ["METER_INSTALL_SCHEDULED"],
  METER_INSTALL_SCHEDULED: ["METER_INSTALLED"],
  METER_INSTALLED: ["CLOSED"],
  EXT_WAITING_SUMMARY: ["EXT_WAITING_HQ_SUBMISSION"],
  EXT_WAITING_HQ_SUBMISSION: ["EXT_SUBMITTED_TO_HQ"],
  EXT_SUBMITTED_TO_HQ: ["EXT_WAITING_DECISION"],
  EXT_WAITING_DECISION: ["NEED_MORE_INFO", "CLOSED"],
  CLOSED: []
};

export const ROLE_PERMISSIONS: Record<RoleCode, string[]> = {
  RECEPTIONIST: ["request.create", "request.assign"],
  SURVEYOR: ["request.document_review", "request.survey_result"],
  OPERATIONS: ["meter.ics", "meter.invoice", "meter.payment"],
  SUPERVISOR: ["dashboard.view", "request.reassign"],
  MANAGER: ["request.approve", "queue.approve"],
  INSTALL_PLANNER: ["queue.create", "queue.assign"]
};
