-- Add canonical statuses for meter 30/100 1 phase workflow
alter table public.service_requests
  drop constraint if exists service_requests_status_check;

alter table public.service_requests
  add constraint service_requests_status_check check (
    status in (
      'NEW', 'PENDING_SURVEY_REVIEW', 'SURVEY_ACCEPTED', 'SURVEY_DOCS_INCOMPLETE', 'SURVEY_RESCHEDULE_REQUESTED', 'SURVEY_COMPLETED',
      'WAIT_LAYOUT_DRAWING', 'WAITING_TO_SEND_TO_KRABI', 'SENT_TO_KRABI', 'WAIT_KRABI_DOCUMENT_CHECK', 'KRABI_NEEDS_DOCUMENT_FIX',
      'KRABI_IN_PROGRESS', 'KRABI_ESTIMATION_COMPLETED', 'BILL_ISSUED', 'COORDINATED_WITH_CONSTRUCTION',
      'WAIT_DOCUMENT_REVIEW', 'WAIT_DOCUMENT_FROM_CUSTOMER', 'READY_FOR_SURVEY', 'IN_SURVEY', 'WAIT_CUSTOMER_FIX', 'WAIT_FIX_REVIEW',
      'READY_FOR_RESURVEY', 'CHECK_3PHASE_CAPABILITY', 'NEEDS_EXPANSION', 'DESIGN_AND_ESTIMATE', 'WAIT_BILLING', 'WAIT_PAYMENT',
      'INSTALLATION', 'INSPECTION', 'WAIT_ACTION_CONFIRMATION', 'WAIT_MANAGER_REVIEW',
      'WAIT_AONANG_MANAGER_PRE_KRABI_APPROVAL', 'WAIT_KRABI_APPROVAL', 'KRABI_NEEDS_CORRECTION', 'DOCUMENT_FIX', 'RESENT_TO_KRABI',
      'KRABI_APPROVED', 'WAIT_RECEIVE_FROM_KRABI', 'WAIT_AONANG_MANAGER_FINAL_APPROVAL', 'COMPLETED'
    )
  );
